#!/bin/sh

# Set these paths appropriately

BIN=/global/nicklaus/fohr/treetagger/bin
CMD=/global/nicklaus/fohr/treetagger/cmd
LIB=/global/nicklaus/fohr/treetagger/lib

POSTAGGER=${CMD}/tree-tagger-english
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/english-chunker.par
FILTER=${CMD}/filter-chunker-output.perl

$POSTAGGER $* |
perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' |
$TAGGER $PARFILE -token -sgml -eps 0.00000001 -hyphen-heuristics -quiet |
$FILTER
