#!/bin/sh

# Set these paths appropriately

BIN=/global/nicklaus/fohr/treetagger/bin
CMD=/global/nicklaus/fohr/treetagger/cmd
LIB=/global/nicklaus/fohr/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

# tagging with Stein's tagger
$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
