#!/bin/sh

# Set these paths appropriately

BIN=/global/nicklaus/fohr/treetagger/bin
CMD=/global/nicklaus/fohr/treetagger/cmd
LIB=/global/nicklaus/fohr/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/bulgarian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
